IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'nhanVien')
CREATE TABLE nhanVien (
    maNhanVien NVARCHAR(50) PRIMARY KEY,
    hoTen NVARCHAR(100),
    chucVu NVARCHAR(100),
    soDienThoai NVARCHAR(15),
    diaChi NVARCHAR(200)
);
