IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'taiKhoan')
CREATE TABLE taiKhoan (
    tenDangNhap NVARCHAR(50) PRIMARY KEY,
    matKhau NVARCHAR(100),
    maNhanVien NVARCHAR(50) FOREIGN KEY REFERENCES nhanVien(maNhanVien)
);
